var paintingsApp = angular.module('paintingsApp', []);

paintingsApp.controller('PaintingListCtrl', function ($scope) {

  $scope.paintings = [
{'number': 1,
'title': 'Le Forgeron',
'imageFile': '001.jpg',
'isPrivate': false},
{'number': 2,
'title': 'Les préparatifs de la noce',
'imageFile': '002.jpg',
'isPrivate': false},
{'number': 3,
'title': 'Le coupeur de lande',
'imageFile': '003.jpg',
'isPrivate': true},
{'number': 4,
'title': 'L\'homme au renard',
'imageFile': '004.jpg',
'isPrivate': false},
{'number': 5,
'title': 'Les faucheurs dans les prairies',
'imageFile': '005.jpg',
'isPrivate': false},
{'number': 7,
'title': 'Les charretiers de camors',
'imageFile': '007.jpg',
'isPrivate': true},
{'number': 8,
'title': 'La charrette tombée',
'imageFile': '008.jpg',
'isPrivate': false},
{'number': 9,
'title': 'La chute du sapin de croix',
'imageFile': '009.jpg',
'isPrivate': false},
{'number': 10,
'title': 'Le sourcier',
'imageFile': '010.jpg',
'isPrivate': true},
{'number': 11,
'title': 'La brouette de colza',
'imageFile': '011.jpg',
'isPrivate': true},
{'number': 12,
'title': 'Le vieux et la jument',
'imageFile': '012.jpg',
'isPrivate': true},
{'number': 13,
'title': 'L\'homme aux champignons',
'imageFile': '013.jpg',
'isPrivate': true},
{'number': 14,
'title': 'Le corbeau et le lavoir',
'imageFile': '014.jpg',
'isPrivate': false},
{'number': 15,
'title': 'La truie et sa portée (la veillée à l\'étable)',
'imageFile': '015.jpg',
'isPrivate': true},
{'number': 16,
'title': 'Les cordiers de baud',
'imageFile': '016.jpg',
'isPrivate': false},
{'number': 17,
'title': 'Les sabotiers de Camors',
'imageFile': '017.jpg',
'isPrivate': true},
{'number': 18,
'title': 'Le vieux et la mécanisation',
'imageFile': '018.jpg',
'isPrivate': false},
{'number': 19,
'title': 'Le réparateur de parapluies',
'imageFile': '019.jpg',
'isPrivate': true},
{'number': 20,
'title': 'Le couvreur de chaume',
'imageFile': '020.jpg',
'isPrivate': true},
{'number': 21,
'title': 'La moisson du blé noir',
'imageFile': '021.jpg',
'isPrivate': true},
{'number': 22,
'title': 'La maison et son potager',
'imageFile': '022.jpg',
'isPrivate': false},
{'number': 23,
'title': 'Fin de l\'hiver à la lande',
'imageFile': '023.jpg',
'isPrivate': false},
{'number': 24,
'title': 'La toilette des prairies',
'imageFile': '024.jpg',
'isPrivate': false},
{'number': 25,
'title': 'A la pépinière',
'imageFile': '025.jpg',
'isPrivate': false},
{'number': 26,
'title': 'Le pardon de Lambézégan (Gwil maria kreis est)',
'imageFile': '026.jpg',
'isPrivate': true},
{'number': 27,
'title': 'La greffe du pommier',
'imageFile': '027.jpg',
'isPrivate': true},
{'number': 28,
'title': 'Le planteur de choux',
'imageFile': '028.jpg',
'isPrivate': false},
{'number': 29,
'title': 'La bouilleur de cru',
'imageFile': '029.jpg',
'isPrivate': false},
{'number': 30,
'title': 'La récolte de la graine de trèfle',
'imageFile': '030.jpg',
'isPrivate': true},
{'number': 31,
'title': 'La pause « cerises »',
'imageFile': '031.jpg',
'isPrivate': false},
{'number': 32,
'title': 'Le dernier coup de faucheuse',
'imageFile': '032.jpg',
'isPrivate': true},
{'number': 33,
'title': 'Septembre à Languidic',
'imageFile': '033.jpg',
'isPrivate': false},
{'number': 34,
'title': 'La récolte de  la pomme à cidre',
'imageFile': '034.jpg',
'isPrivate': false},
{'number': 35,
'title': 'Le défrichage mécanique',
'imageFile': '035.jpg',
'isPrivate': true},
{'number': 36,
'title': 'Veille de Noël',
'imageFile': '036.jpg',
'isPrivate': true},
{'number': 37,
'title': 'Les vaches à la lande (combat de vaches)',
'imageFile': '037.jpg',
'isPrivate': false},
{'number': 38,
'title': 'Le couvreur de chaume',
'imageFile': '038.jpg',
'isPrivate': true},
{'number': 39,
'title': 'Préparation du potager',
'imageFile': '039.jpg',
'isPrivate': true},
{'number': 40,
'title': 'En voiture pour le marché',
'imageFile': '040.jpg',
'isPrivate': true},
{'number': 41,
'title': 'Le pardon de Saint-Eloi',
'imageFile': '041.jpg',
'isPrivate': true},
{'number': 42,
'title': 'Le cerclage des roues',
'imageFile': '042.jpg',
'isPrivate': true},
{'number': 43,
'title': 'La derniere charretée de foin',
'imageFile': '043.jpg',
'isPrivate': true},
{'number': 44,
'title': 'La mise en gerbe du seigle',
'imageFile': '044.jpg',
'isPrivate': true},
{'number': 46,
'title': 'Le déménagement du fermier',
'imageFile': '046.jpg',
'isPrivate': true},
{'number': 47,
'title': 'L\'expédition des pommes à cidre La gare de Baud',
'imageFile': '047.jpg',
'isPrivate': true},
{'number': 48,
'title': 'Pont-Augan',
'imageFile': '048.jpg',
'isPrivate': true},
{'number': 49,
'title': 'Les charbonniers dans les taillis',
'imageFile': '049.jpg',
'isPrivate': false},
{'number': 50,
'title': 'Arrivée du paysan de bord de mer',
'imageFile': '050.jpg',
'isPrivate': true},
{'number': 51,
'title': 'Le poulain au pré',
'imageFile': '051.jpg',
'isPrivate': true},
{'number': 52,
'title': 'Le printemps à Kerscoul',
'imageFile': '052.jpg',
'isPrivate': true},
{'number': 53,
'title': 'La lessive de Printemps',
'imageFile': '053.jpg',
'isPrivate': true},
{'number': 54,
'title': 'La garde des abeilles',
'imageFile': '054.jpg',
'isPrivate': true},
{'number': 55,
'title': 'La pause moisson',
'imageFile': '055.jpg',
'isPrivate': true},
{'number': 56,
'title': 'Le battage du blé noir',
'imageFile': '056.jpg',
'isPrivate': true},
{'number': 57,
'title': 'La rentrée des classes',
'imageFile': '057.jpg',
'isPrivate': true},
{'number': 58,
'title': 'La chasse à l\'écureuil',
'imageFile': '058.jpg',
'isPrivate': false},
{'number': 59,
'title': 'Le curage du Penerh (cour de ferme)',
'imageFile': '059.jpg',
'isPrivate': false},
{'number': 60,
'title': 'La mise en meule',
'imageFile': '060.jpg',
'isPrivate': true},
{'number': 61,
'title': 'La chasse aux doryphores',
'imageFile': '061.jpg',
'isPrivate': true},
{'number': 62,
'title': 'Les travaux du vendredi saint',
'imageFile': null,
'isPrivate': false},
{'number': 63,
'title': 'Le facteur au village',
'imageFile': '063.jpg',
'isPrivate': true},
{'number': 64,
'title': 'Le battage « mécanique »',
'imageFile': '064.jpg',
'isPrivate': true},
{'number': 65,
'title': 'La vente de la St Michel',
'imageFile': '065.jpg',
'isPrivate': true},
{'number': 66,
'title': 'Les charretiers en foret',
'imageFile': '066.jpg',
'isPrivate': true},
{'number': 67,
'title': 'Le filaj Veillée d\'hiver',
'imageFile': '067.jpg',
'isPrivate': true},
{'number': 68,
'title': 'L arrachage des pommes de terre',
'imageFile': '068.jpg',
'isPrivate': true},
{'number': 70,
'title': 'Le chasseur dans la neige',
'imageFile': '070.jpg',
'isPrivate': true},
{'number': 71,
'title': 'L\'heure de la messe (Avant la messe)',
'imageFile': '071.jpg',
'isPrivate': true},
{'number': 72,
'title': 'La vache étranglée',
'imageFile': '072.jpg',
'isPrivate': false},
{'number': 73,
'title': 'La coupe de bois de chauffe',
'imageFile': '073.jpg',
'isPrivate': true},
{'number': 77,
'title': 'La leçon de choses (dans la cour de l\'école)',
'imageFile': '077.jpg',
'isPrivate': false},
{'number': 78,
'title': 'L\'arrivée de la batteuse',
'imageFile': '078.jpg',
'isPrivate': true},
{'number': 79,
'title': 'Le binage de printemps',
'imageFile': '079.jpg',
'isPrivate': true},
{'number': 80,
'title': 'Le sport d\'hiver',
'imageFile': '080.jpg',
'isPrivate': true},
{'number': 81,
'title': 'Les vaches et la lande (fin de l\'hiver)',
'imageFile': '081.jpg',
'isPrivate': false},
{'number': 83,
'title': 'Le village de dos',
'imageFile': '083.jpg',
'isPrivate': true},
{'number': 84,
'title': 'sur le sentier de l\'école (le retour)',
'imageFile': '084.jpg',
'isPrivate': false},
{'number': 85,
'title': 'La course cycliste',
'imageFile': '085.jpg',
'isPrivate': true},
{'number': 86,
'title': 'L\'installation des ruches',
'imageFile': '086.jpg',
'isPrivate': false},
{'number': 87,
'title': 'La démolition d\'un talus',
'imageFile': '087.jpg',
'isPrivate': true},
{'number': 88,
'title': 'Village sous la neige (chapelle)',
'imageFile': '088.jpg',
'isPrivate': false},
{'number': 89,
'title': 'L\'écluse de Pont-Augan (Ste Barbe)',
'imageFile': '089.jpg',
'isPrivate': false},
{'number': 90,
'title': 'Le moulin à eau de Morsaï',
'imageFile': '090.jpg',
'isPrivate': true},
{'number': 91,
'title': 'Le pardon de Saint-Éloi (la bénédiction)',
'imageFile': '091.jpg',
'isPrivate': true},
{'number': 92,
'title': 'La fabrication du cidre (à l\'intérieur)',
'imageFile': '092.jpg',
'isPrivate': false},
{'number': 93,
'title': 'L ecluse de Minazen (sous la neige)',
'imageFile': '093.jpg',
'isPrivate': true},
{'number': 94,
'title': 'Le défrichage manuel',
'imageFile': '094.jpg',
'isPrivate': true},
{'number': 95,
'title': 'On tue le cochon',
'imageFile': '095.jpg',
'isPrivate': true},
{'number': 97,
'title': 'Le feu à Lambézégan',
'imageFile': '097.jpg',
'isPrivate': true},
{'number': 98,
'title': 'La moisson du blé noir',
'imageFile': '098.jpg',
'isPrivate': false},
{'number': 99,
'title': 'La neige sur l\'aire à battre',
'imageFile': '099.jpg',
'isPrivate': true},
{'number': 100,
'title': 'Le cheval emballé',
'imageFile': '100.jpg',
'isPrivate': true},
{'number': 101,
'title': 'L\'hospice des années 50',
'imageFile': '101.jpg',
'isPrivate': false},
{'number': 102,
'title': 'Le graissage de l essieu',
'imageFile': '102.jpg',
'isPrivate': false},
{'number': 103,
'title': 'La « tenue » de l\'ouvrier agricole',
'imageFile': '103.jpg',
'isPrivate': true},
{'number': 104,
'title': 'Tir à la corde',
'imageFile': '104.jpg',
'isPrivate': true},
{'number': 105,
'title': 'Un dimanche après-midi (durant la moisson)',
'imageFile': '105.jpg',
'isPrivate': false},
{'number': 106,
'title': 'La pause repas (durant la moisson)',
'imageFile': '106.jpg',
'isPrivate': false},
{'number': 107,
'title': 'Paysage hivernal',
'imageFile': '107.jpg',
'isPrivate': false},
{'number': 109,
'title': 'Le travail du chanvre',
'imageFile': '109.jpg',
'isPrivate': false},
{'number': 110,
'title': 'Midi sonne',
'imageFile': '110.jpg',
'isPrivate': true},
{'number': 111,
'title': 'Le dindon et le facteur',
'imageFile': '111.jpg',
'isPrivate': true},
{'number': 112,
'title': 'La baignade à l\'ével',
'imageFile': '112.jpg',
'isPrivate': true},
{'number': 113,
'title': 'L\'horloge des champs',
'imageFile': '113.jpg',
'isPrivate': true},
{'number': 114,
'title': 'À la châtaigneraie',
'imageFile': '114.jpg',
'isPrivate': true},
{'number': 115,
'title': 'La veillée du mort',
'imageFile': '115.jpg',
'isPrivate': true},
{'number': 116,
'title': 'La toilette du cheval',
'imageFile': '116.jpg',
'isPrivate': true},
{'number': 118,
'title': 'La vache au taureau',
'imageFile': '118.jpg',
'isPrivate': false},
{'number': 119,
'title': 'La pause coup de cidre',
'imageFile': '119.jpg',
'isPrivate': false},
{'number': 120,
'title': 'Noce dans l\'aire à battre',
'imageFile': '120.jpg',
'isPrivate': true},
{'number': 122,
'title': 'Le battage mécanique',
'imageFile': '122.jpg',
'isPrivate': true},
{'number': 123,
'title': 'La rentrée d automne (la corvée)',
'imageFile': '123.jpg',
'isPrivate': false},
{'number': 124,
'title': 'Il a neigé sur la lande',
'imageFile': '124.jpg',
'isPrivate': true},
{'number': 125,
'title': 'Kerdaniel sous la neige',
'imageFile': '125.jpg',
'isPrivate': false},
{'number': 126,
'title': 'L\'heure du repas des bêtes',
'imageFile': '126.jpg',
'isPrivate': true},
{'number': 127,
'title': 'Le tri des pommes de terre',
'imageFile': '127.jpg',
'isPrivate': false},
{'number': 128,
'title': 'Au temps du trèfle incarnat',
'imageFile': '128.jpg',
'isPrivate': true},
{'number': 129,
'title': 'le Bugul et son chien',
'imageFile': '129.jpg',
'isPrivate': true},
{'number': 130,
'title': 'Dans les prairies humides',
'imageFile': '130.jpg',
'isPrivate': false},
{'number': 131,
'title': 'La cueillette des cèpes',
'imageFile': '131.jpg',
'isPrivate': false},
{'number': 132,
'title': 'Les Bohémiens sont arrivés',
'imageFile': '132.jpg',
'isPrivate': true},
{'number': 133,
'title': 'Fendaisons des troncs',
'imageFile': '133.jpg',
'isPrivate': true},
{'number': 134,
'title': 'Un matin de février',
'imageFile': '134.jpg',
'isPrivate': false},
{'number': 135,
'title': 'Les primevères',
'imageFile': '135.jpg',
'isPrivate': true},
{'number': 136,
'title': 'Les orchidées : les prairies en main',
'imageFile': '136.jpg',
'isPrivate': false},
{'number': 137,
'title': 'La partie de boules',
'imageFile': '137.jpg',
'isPrivate': true},
{'number': 138,
'title': 'L approche du sarrasin',
'imageFile': '138.jpg',
'isPrivate': false},
{'number': 139,
'title': 'La fabrication du cidre le manège',
'imageFile': '139.jpg',
'isPrivate': true},
{'number': 140,
'title': 'Le moulin de Guerzelin',
'imageFile': '140.jpg',
'isPrivate': true},
{'number': 141,
'title': 'La chapelle de St Jean',
'imageFile': '141.jpg',
'isPrivate': true},
{'number': 142,
'title': 'Le travail du bois',
'imageFile': '142.jpg',
'isPrivate': false},
{'number': 143,
'title': 'La coupe de cheveux',
'imageFile': '143.jpg',
'isPrivate': false},
{'number': 144,
'title': 'Les vaches folles',
'imageFile': '144.jpg',
'isPrivate': false},
{'number': 145,
'title': 'La messe a l\'église de Kergonan',
'imageFile': '145.jpg',
'isPrivate': true},
{'number': 146,
'title': 'Le petit train des champs',
'imageFile': '146.jpg',
'isPrivate': true},
{'number': 147,
'title': 'Les vaches à l\'eau',
'imageFile': '147.jpg',
'isPrivate': false},
{'number': 148,
'title': 'Dans la forge',
'imageFile': '148.jpg',
'isPrivate': false},
{'number': 149,
'title': 'La chapelle de Pen Hoët',
'imageFile': '149.jpg',
'isPrivate': true},
{'number': 150,
'title': 'Le travail du fumier',
'imageFile': '150.jpg',
'isPrivate': true},
{'number': 152,
'title': 'Repas à l\'ombre',
'imageFile': '152.jpg',
'isPrivate': false},
{'number': 153,
'title': 'Le jardin de ma tante',
'imageFile': '153.jpg',
'isPrivate': true},
{'number': 154,
'title': 'La corvée de bois',
'imageFile': '154.jpg',
'isPrivate': false},
{'number': 155,
'title': 'Neige au clair de lune',
'imageFile': '155.jpg',
'isPrivate': false},
{'number': 156,
'title': 'dans le fournil',
'imageFile': '156.jpg',
'isPrivate': false},
{'number': 157,
'title': 'La pause conversation',
'imageFile': '157.jpg',
'isPrivate': true},
{'number': 158,
'title': 'Les quatre saisons',
'imageFile': '158.jpg',
'isPrivate': true},
{'number': 160,
'title': 'Les quatre saisons',
'imageFile': '160.jpg',
'isPrivate': true},
{'number': 161,
'title': 'Les quatre saisons',
'imageFile': '161.jpg',
'isPrivate': true},
{'number': 162,
'title': 'Travaux de février (dans les prairies)',
'imageFile': '162.jpg',
'isPrivate': false},
{'number': 163,
'title': 'Les quatre saisons',
'imageFile': '163.jpg',
'isPrivate': true},
{'number': 164,
'title': 'Le repas des lapins (l\'initiation)',
'imageFile': '164.jpg',
'isPrivate': true},
{'number': 165,
'title': 'Le dressage du jeune cheval',
'imageFile': '165.jpg',
'isPrivate': false},
{'number': 166,
'title': 'Les enfants de Kergonan (sur le chemin de l\'école)',
'imageFile': '166.jpg',
'isPrivate': false},
{'number': 167,
'title': 'le battage au village',
'imageFile': '167.jpg',
'isPrivate': true},
{'number': 168,
'title': 'L\'homme à la houe (Le sabot et la pause)',
'imageFile': '168.jpg',
'isPrivate': true},
{'number': 169,
'title': 'La femme au râteau (Le sabot et la pause)',
'imageFile': '169.jpg',
'isPrivate': true},
{'number': 170,
'title': 'A la pépinière (arrachage du plant de pommier)',
'imageFile': '170.jpg',
'isPrivate': false},
{'number': 171,
'title': 'Le ferrage du sabot de bois',
'imageFile': '171.jpg',
'isPrivate': false},
{'number': 172,
'title': 'Glissade sur la prairie gelée',
'imageFile': '172.jpg',
'isPrivate': true},
{'number': 173,
'title': 'Le débroussailleur',
'imageFile': '173.jpg',
'isPrivate': false},
{'number': 174,
'title': 'les charretiers au travail',
'imageFile': '174.jpg',
'isPrivate': false},
{'number': 175,
'title': 'Le poulain avec sa mère',
'imageFile': '175.jpg',
'isPrivate': false},
{'number': 176,
'title': 'La rentrée des foins',
'imageFile': '176.jpg',
'isPrivate': true},
{'number': 177,
'title': 'La lutte bretonne',
'imageFile': '177.jpg',
'isPrivate': true},
{'number': 178,
'title': 'L\'automne',
'imageFile': '178.jpg',
'isPrivate': false},
{'number': 179,
'title': 'Les cabanes sous la neige',
'imageFile': '179.jpg',
'isPrivate': false},
{'number': 180,
'title': 'Kergonan et son cimetière',
'imageFile': '180.jpg',
'isPrivate': true},
{'number': 181,
'title': 'L\'arrivée du chemin de fer',
'imageFile': '181.jpg',
'isPrivate': false},
{'number': 182,
'title': 'Le contournement du pommier',
'imageFile': '182.jpg',
'isPrivate': false},
{'number': 183,
'title': 'En route pour le certificat d\'études',
'imageFile': '183.jpg',
'isPrivate': true},
{'number': 184,
'title': 'Portrait de famille',
'imageFile': '184.jpg',
'isPrivate': true},
{'number': 185,
'title': 'L\'heure de la traite',
'imageFile': '185.jpg',
'isPrivate': false},
{'number': 186,
'title': 'Neige sur les têtards',
'imageFile': '186.jpg',
'isPrivate': false},
{'number': 187,
'title': 'La récolte de la litière',
'imageFile': '187.jpg',
'isPrivate': false},
{'number': 188,
'title': 'Les trois chantiers de la lande',
'imageFile': '188.jpg',
'isPrivate': true},
{'number': 189,
'title': 'Dans “les Flouren”',
'imageFile': '189.jpg',
'isPrivate': false},
{'number': 190,
'title': 'Mouvements d\'ensemble',
'imageFile': '190.jpg',
'isPrivate': false},
{'number': 191,
'title': 'Le serrage de la charretée de foin',
'imageFile': '191.jpg',
'isPrivate': false},
{'number': 192,
'title': 'La mise en gerbes',
'imageFile': '192.jpg',
'isPrivate': false},
{'number': 193,
'title': 'La récolte des pommes de terre',
'imageFile': '193.jpg',
'isPrivate': true},
{'number': 194,
'title': 'Soirée cinéma dans le bistrot',
'imageFile': '194.jpg',
'isPrivate': false},
{'number': 195,
'title': 'La scierie locale',
'imageFile': '195.jpg',
'isPrivate': false},
{'number': 196,
'title': 'La récolte du lierre et du houx',
'imageFile': '196.jpg',
'isPrivate': false},
{'number': 197,
'title': 'Le cheval au repos (par mauvais temps)',
'imageFile': '197.jpg',
'isPrivate': false},
{'number': 198,
'title': 'La pause binage',
'imageFile': '198.jpg',
'isPrivate': false},
{'number': 199,
'title': 'Traversée d\'une zone humide',
'imageFile': '199.jpg',
'isPrivate': true},
{'number': 200,
'title': 'La fenaison du trèfle incarnat',
'imageFile': '200.jpg',
'isPrivate': true},
{'number': 201,
'title': 'Sur le chemin des aveugles',
'imageFile': '201.jpg',
'isPrivate': false},
{'number': 202,
'title': 'L\'attaque d\'un essaim de guêpes',
'imageFile': '202.jpg',
'isPrivate': false},
{'number': 203,
'title': 'La partie de “Velat”',
'imageFile': '203.jpg',
'isPrivate': true},
{'number': 204,
'title': 'Le cochon pendu',
'imageFile': '204.jpg',
'isPrivate': false},
{'number': 205,
'title': 'Le chantier du chemin de fer',
'imageFile': '205.jpg',
'isPrivate': false},
{'number': 206,
'title': 'Lambézégan sous la neige',
'imageFile': '206.jpg',
'isPrivate': false},
{'number': 207,
'title': 'Le broyage de l\'ajonc',
'imageFile': '207.jpg',
'isPrivate': true},
{'number': 208,
'title': 'Le petit cirque s\'installe',
'imageFile': '208.jpg',
'isPrivate': false},
{'number': 209,
'title': 'Le baraquement de réfugiés',
'imageFile': '209.jpg',
'isPrivate': false},
{'number': 210,
'title': 'Le demi-tour',
'imageFile': '210.jpg',
'isPrivate': false},
{'number': 211,
'title': 'Autour du lavoir',
'imageFile': '211.jpg',
'isPrivate': false},
{'number': 212,
'title': 'Le poulain avec sa mère',
'imageFile': '212.jpg',
'isPrivate': false},
{'number': 213,
'title': 'La bénédiction des champs',
'imageFile': '213.jpg',
'isPrivate': true},
{'number': 214,
'title': 'Le blé noir en fleurs',
'imageFile': '214.jpg',
'isPrivate': true},
{'number': 215,
'title': 'La pause des faucheurs',
'imageFile': '215.jpg',
'isPrivate': false},
{'number': 216,
'title': 'La moisson de seigle',
'imageFile': '216.jpg',
'isPrivate': true},
{'number': 217,
'title': 'Battage au manège',
'imageFile': '217.jpg',
'isPrivate': false},
{'number': 218,
'title': 'La moisson du blé noir',
'imageFile': '218.jpg',
'isPrivate': true},
{'number': 219,
'title': 'Jeux avec les vaches',
'imageFile': '219.jpg',
'isPrivate': false},
{'number': 220,
'title': 'Le réparateur de parapluies',
'imageFile': '220.jpg',
'isPrivate': true},
{'number': 221,
'title': 'Retour de la foire de Bubry',
'imageFile': '221.jpg',
'isPrivate': false},
{'number': 222,
'title': 'Récolte de la litière',
'imageFile': '222.jpg',
'isPrivate': false},
{'number': 223,
'title': 'Le sentier sur le talus',
'imageFile': null,
'isPrivate': false},
{'number': 224,
'title': 'Ferme de face sous la neige',
'imageFile': '224.jpg',
'isPrivate': false},
{'number': 225,
'title': 'Le petit cirque en séance',
'imageFile': '225.jpg',
'isPrivate': false},
{'number': 226,
'title': 'La pause bistrot',
'imageFile': '226.jpg',
'isPrivate': false},
{'number': 227,
'title': 'Sabotiers en foret',
'imageFile': '227.jpg',
'isPrivate': false},
{'number': 228,
'title': 'La tourbière',
'imageFile': '228.jpg',
'isPrivate': true},
{'number': 229,
'title': 'Sur le sentier de l\'école, Passage du gué (Pontigeu)',
'imageFile': '229.jpg',
'isPrivate': false},
{'number': 230,
'title': 'Le moulin du resto',
'imageFile': '230.jpg',
'isPrivate': false},
{'number': 231,
'title': 'Un jeudi du mois de mai',
'imageFile': '231.jpg',
'isPrivate': true},
{'number': 232,
'title': 'Les digitales',
'imageFile': '232.jpg',
'isPrivate': false},
{'number': 233,
'title': 'Les grands travaux de l\'été',
'imageFile': '233.jpg',
'isPrivate': true},
{'number': 234,
'title': 'La foire de Saint Germain',
'imageFile': '234.jpg',
'isPrivate': true},
{'number': 235,
'title': 'La conduite du troupeau',
'imageFile': '235.jpg',
'isPrivate': true},
{'number': 236,
'title': 'Travaux d\'octobre',
'imageFile': '236.jpg',
'isPrivate': true},
{'number': 237,
'title': 'Bouleaux en zone humide',
'imageFile': '237.jpg',
'isPrivate': true},
{'number': 238,
'title': 'Pont Augan sous la neige (côté Languidic rive gauche)',
'imageFile': '238.jpg',
'isPrivate': true},
{'number': 239,
'title': 'Vers le cimetière',
'imageFile': '239.jpg',
'isPrivate': true},
{'number': 240,
'title': 'Rencontre dans la lande',
'imageFile': '240.jpg',
'isPrivate': false},
{'number': 241,
'title': 'La classe',
'imageFile': '241.jpg',
'isPrivate': false},
{'number': 242,
'title': 'Le jeu du neuf trous',
'imageFile': '242.jpg',
'isPrivate': false},
{'number': 243,
'title': 'Les dénicheurs',
'imageFile': '243.jpg',
'isPrivate': true},
{'number': 244,
'title': 'L\'oseille sauvage en avril',
'imageFile': '244.jpg',
'isPrivate': false},
{'number': 245,
'title': 'Jacinthes en sous bois',
'imageFile': '245.jpg',
'isPrivate': false},
{'number': 246,
'title': 'Les doryphores',
'imageFile': '246.jpg',
'isPrivate': false},
{'number': 247,
'title': 'Les sardines arrivent',
'imageFile': '247.jpg',
'isPrivate': false},
{'number': 248,
'title': 'Début juillet',
'imageFile': '248.jpg',
'isPrivate': false},
{'number': 249,
'title': 'Baignade à Pont Augan',
'imageFile': '249.jpg',
'isPrivate': false},
{'number': 250,
'title': 'Le désenclavement',
'imageFile': '250.jpg',
'isPrivate': true},
{'number': 251,
'title': 'Battage du blé noir au fléau',
'imageFile': '251.jpg',
'isPrivate': false},
{'number': 252,
'title': 'La récolte des châtaignes',
'imageFile': '252.jpg',
'isPrivate': false},
{'number': 253,
'title': 'Neige sur la vallée',
'imageFile': '253.jpg',
'isPrivate': false},
{'number': 254,
'title': 'Travaux d\'hiver',
'imageFile': '254.jpg',
'isPrivate': true},
{'number': 255,
'title': 'Les poseurs de piège',
'imageFile': '255.jpg',
'isPrivate': false},
{'number': 256,
'title': 'La communion',
'imageFile': '256.jpg',
'isPrivate': false},
{'number': 257,
'title': 'L\'incendie dans la lande',
'imageFile': '257.jpg',
'isPrivate': false},
{'number': 258,
'title': 'Travaux d\'avril',
'imageFile': '258.jpg',
'isPrivate': true},
{'number': 259,
'title': 'Village de Kervarin',
'imageFile': '259.jpg',
'isPrivate': true},
{'number': 260,
'title': 'Le blavet et son halage (vue du halage)',
'imageFile': '260.jpg',
'isPrivate': false},
{'number': 261,
'title': 'Le blavet et son halage (vue des prairies)',
'imageFile': '261.jpg',
'isPrivate': false},
{'number': 262,
'title': 'Kerscoul d\'en haut',
'imageFile': '262.jpg',
'isPrivate': false},
{'number': 263,
'title': 'Le griffon',
'imageFile': '263.jpg',
'isPrivate': false},
{'number': 264,
'title': 'Pont Augan en automne',
'imageFile': '264.jpg',
'isPrivate': true},
{'number': 265,
'title': 'Inondation à Pont Augan',
'imageFile': '265.jpg',
'isPrivate': true},
{'number': 266,
'title': 'l\'automne s\'installe',
'imageFile': '266.jpg',
'isPrivate': true},
{'number': 267,
'title': 'Autour des fagots',
'imageFile': '267.jpg',
'isPrivate': false},
{'number': 268,
'title': 'Kannamb Noël',
'imageFile': '268.jpg',
'isPrivate': true},
{'number': 269,
'title': 'Travaux de février',
'imageFile': '269.jpg',
'isPrivate': true},
{'number': 270,
'title': 'l\'hiver dans les friches',
'imageFile': '270.jpg',
'isPrivate': false},
{'number': 271,
'title': 'Les grands travaux de printemps',
'imageFile': '271.jpg',
'isPrivate': false},
{'number': 273,
'title': 'Dans les prairies fin juin',
'imageFile': '273.jpg',
'isPrivate': false},
{'number': 274,
'title': 'Sur la route de Sainte Anne',
'imageFile': '274.jpg',
'isPrivate': false},
{'number': 275,
'title': 'Fin de l\'été',
'imageFile': '275.jpg',
'isPrivate': false},
{'number': 276,
'title': 'Arrachage des pommes de terre',
'imageFile': '276.jpg',
'isPrivate': false},
{'number': 277,
'title': 'La grande échelle',
'imageFile': '277.jpg',
'isPrivate': false},
{'number': 278,
'title': 'Mi-octobre',
'imageFile': '278.jpg',
'isPrivate': true},
{'number': 279,
'title': 'Mi-novembre',
'imageFile': '279.jpg',
'isPrivate': false},
{'number': 280,
'title': 'Mi-décembre',
'imageFile': '280.jpg',
'isPrivate': true},
{'number': 281,
'title': 'La lande des Korrigans',
'imageFile': '281.jpg',
'isPrivate': false},
{'number': 282,
'title': 'Première neige de décembre',
'imageFile': '282.jpg',
'isPrivate': false},
{'number': 283,
'title': 'La cantine d\'avant 1950',
'imageFile': '283.jpg',
'isPrivate': false},
{'number': 284,
'title': 'Le bocage mi-janvier',
'imageFile': '284.jpg',
'isPrivate': false},
{'number': 285,
'title': 'Cerisiers d\'avril',
'imageFile': '285.jpg',
'isPrivate': true},
{'number': 286,
'title': 'Les pommiers de mai',
'imageFile': '286.jpg',
'isPrivate': false},
{'number': 287,
'title': 'Saint Nicolas et sa chapelle',
'imageFile': '287.jpg',
'isPrivate': true},
{'number': 289,
'title': 'Neiges d\'été',
'imageFile': '289.jpg',
'isPrivate': false},
{'number': 290,
'title': 'La récolte de la graine de trèfle',
'imageFile': '290.jpg',
'isPrivate': false},
{'number': 291,
'title': 'Le jaune de septembre',
'imageFile': '291.jpg',
'isPrivate': false},
{'number': 292,
'title': 'La récolte de la pomme à cidre',
'imageFile': '292.jpg',
'isPrivate': false},
{'number': 293,
'title': 'Fin novembre',
'imageFile': '293.jpg',
'isPrivate': false},
{'number': 294,
'title': 'Neige sur la tourbière',
'imageFile': '294.jpg',
'isPrivate': false},
{'number': 295,
'title': 'Le "Filaj" dans l\'étable',
'imageFile': '295.jpg',
'isPrivate': false},
{'number': 296,
'title': 'Janvier en gris',
'imageFile': '296.jpg',
'isPrivate': false},
{'number': 297,
'title': 'L\'arrachage du pommier',
'imageFile': '297.jpg',
'isPrivate': false},
{'number': 298,
'title': 'Le pardon de Saint-Eloi',
'imageFile': '298.jpg',
'isPrivate': true},
{'number': 299,
'title': 'Les travaux du vendredi saint',
'imageFile': '299.jpg',
'isPrivate': false},
{'number': 300,
'title': 'Le défrichage à 3 chevaux',
'imageFile': '300.jpg',
'isPrivate': false},
{'number': 301,
'title': 'La lande mi-mai',
'imageFile': '301.jpg',
'isPrivate': true},
{'number': 302,
'title': 'Les bohémiens en transit',
'imageFile': '302.jpg',
'isPrivate': false},
{'number': 303,
'title': 'La faucheuse dans la prairie',
'imageFile': '303.jpg',
'isPrivate': false},
{'number': 304,
'title': 'Le retour des charretiers',
'imageFile': '304.jpg',
'isPrivate': false},
{'number': 305,
'title': 'mi-septembre',
'imageFile': '305.jpg',
'isPrivate': true},
{'number': 306,
'title': 'La tourbière fin septembre',
'imageFile': '306.jpg',
'isPrivate': false},
{'number': 307,
'title': 'La tourbière fin novembre',
'imageFile': '307.jpg',
'isPrivate': false},
{'number': 308,
'title': 'La tourbière fin décembre',
'imageFile': '308.jpg',
'isPrivate': false},
{'number': 309,
'title': 'Les bohémiens dans le froid',
'imageFile': '309.jpg',
'isPrivate': false},
{'number': 310,
'title': 'Le taillis de chênes',
'imageFile': '310.jpg',
'isPrivate': false},
{'number': 311,
'title': 'Sur la route de l\'école (du bon dieu)',
'imageFile': '311.jpg',
'isPrivate': false},
{'number': 312,
'title': 'Le chantier des genets',
'imageFile': '312.jpg',
'isPrivate': false},
{'number': 313,
'title': 'Février en gris',
'imageFile': '313.jpg',
'isPrivate': false},
{'number': 314,
'title': 'Les flourennes en mars',
'imageFile': '314.jpg',
'isPrivate': false},
{'number': 315,
'title': 'Les bouleaux d\'avril',
'imageFile': '315.jpg',
'isPrivate': false},
{'number': 316,
'title': 'La lande se réveille',
'imageFile': null,
'isPrivate': false},
{'number': 317,
'title': 'La semaille des betteraves',
'imageFile': '317.jpg',
'isPrivate': false},
{'number': 318,
'title': 'De Pont-augan à Quistinic',
'imageFile': '318.jpg',
'isPrivate': false},
{'number': 319,
'title': 'Le pardon des chevaux dans la lande',
'imageFile': '319.jpg',
'isPrivate': false},
{'number': 320,
'title': 'La partie de « vellat » dans la lande',
'imageFile': '320.jpg',
'isPrivate': false},
{'number': 321,
'title': 'Octobre dans la lande',
'imageFile': '321.jpg',
'isPrivate': false},
{'number': 322,
'title': 'L\'hiver du coupeur de lande',
'imageFile': '322.jpg',
'isPrivate': false},
{'number': 323,
'title': 'Les corbeaux de novembre',
'imageFile': '323.jpg',
'isPrivate': false},
{'number': 324,
'title': 'La lande sous la neige',
'imageFile': '324.jpg',
'isPrivate': false},
{'number': 325,
'title': 'Les landes de Lanveur autrefois',
'imageFile': '325.jpg',
'isPrivate': false},
{'number': 326,
'title': 'Février, la soudure',
'imageFile': '326.jpg',
'isPrivate': false},
{'number': 327,
'title': 'Février – au service du troupeau',
'imageFile': '327.jpg',
'isPrivate': false},
{'number': 328,
'title': 'Un jeudi de février dans la lande',
'imageFile': '328.jpg',
'isPrivate': false},
{'number': 329,
'title': 'Février dans le « Lannec »',
'imageFile': '329.jpg',
'isPrivate': false},
{'number': 330,
'title': 'Les primevères autrefois',
'imageFile': '330.jpg',
'isPrivate': false},
{'number': 331,
'title': 'les jacinthes dans les friches',
'imageFile': '331.jpg',
'isPrivate': false},
{'number': 332,
'title': 'Le réveil des chênes',
'imageFile': '332.jpg',
'isPrivate': false},
{'number': 333,
'title': 'Un coin de lande humide',
'imageFile': '333.jpg',
'isPrivate': false},
{'number': 334,
'title': 'Lande et pins maritimes',
'imageFile': '334.jpg',
'isPrivate': false},
{'number': 335,
'title': 'La lande fin juin',
'imageFile': '335.jpg',
'isPrivate': false},
{'number': 336,
'title': 'Prairies et landes début juillet',
'imageFile': '336.jpg',
'isPrivate': false},
{'number': 337,
'title': 'L\'automne sur la lande',
'imageFile': '337.jpg',
'isPrivate': false
}
];

$scope.paintings = partition($scope.paintings, 6);
});

function partition(arr, size) {
  var newArr = [];
  for (var i=0; i<arr.length; i+=size) {
    newArr.push(arr.slice(i, i+size));
  }
  return newArr;
}